#ifndef RESOURCE_H_INCLUDED
#define RESOURCE_H_INCLUDED

#define STR_MAX_LENGTH 255

//ID static text controls
#define IDS_FRAMECLASSNAME 0
#define IDS_FRAMEWINDOWCAPTION 1
#define IDS_MDICLIENT 2

#endif // RESOURCE_H_INCLUDED
